
on:
  push:
    branches:
      - master

name: Deploy to firebase
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install firebase tools
      run: |
        echo $(pwd)
        sudo npm install -g firebase-tools

    - name: Install dependencies
      run:  npm install
    - name: Build project
      run: npm run build

    - name: Deploy to firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        echo $(ls)
        sudo firebase deploy -token $FIREBASE_TOKEN
