name: Build and Deploy
on:
  push:
    branches:
      - master

name: Deploy to firebase
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run:  npm install
    - name: Install firebase tools
      run:  npm install -g firebase-tools
    - name: Deploy to firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy -token $FIREBASE_TOKEN
